headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: Longform
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - link
  - underline
  - numberedList
  - bulletedList
  - insertTable
  - '|'
  - createEntry
  - '|'
  - sourceEditing
