tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-07-21T16:48:41+01:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 33dc3204-13eb-4232-9347-3c2c06e052b1
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-07-21T16:48:41+01:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 5d202af8-c8bc-4fa4-b135-f48b6e72ac78
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-07-21T16:48:41+01:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 33de0dc8-a8c4-4262-bbe0-13ebd91a3d40
        userCondition: null
        warning: null
    name: Content
    uid: 9b58f65c-ac9e-4489-9dd8-f21f213efbef
    userCondition: null
